In [11]:
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
datos_modelo = pd.read_csv('datos_completos_samsung_final.csv')

In [13]:
datos_modelo.head(5)

pdv_id  mes_id  sku_id  ventas_totales  y_ventas_siguiente_mes  \
0       1       0       1               1                       0   
1       1       1       1               0                       0   
2       1       2       1               0                       0   
3       1       3       1               0                       0   
4       1       4       1               0                       0   

   ventas_totales_en_tienda_de_cada_mes  \
0                                     2   
1                                     1   
2                                     7   
3                                     7   
4                                    12   

   ventas_promedio_en_tienda_de_cada_mes  \
0                               0.055556   
1                               0.027778   
2                               0.194444   
3                               0.194444   
4                               0.333333   

   ventas_totales_en_tienda_de_cada_sku  \
0                                   741   
1                                   714   
2                                   239   
3                                   110   
4                                    58   

   ventas_promedio_en_tienda_de_cada_sku  ventas_totales_1_mes_pasado  ...  \
0                               0.413274                            1  ...   
1                               0.398215                            1  ...   
2                               0.133296                            0  ...   
3                               0.061350                            0  ...   
4                               0.032348                            0  ...   

   ventas_totales_tienda_y_mes_3_pasado  \
0                                     2   
1                                     2   
2                                     2   
3                                     2   
4                                     1   

   ventas_promedio_tienda_y_mes_del_mes_pasado  \
0                                     0.055556   
1                                     0.055556   
2                                     0.027778   
3                                     0.194444   
4                                     0.194444   

   ventas_promedio_tienda_y_mes_2_pasado  \
0                               0.055556   
1                               0.055556   
2                               0.055556   
3                               0.027778   
4                               0.194444   

   ventas_promedio_tienda_y_mes_3_pasado  \
0                               0.055556   
1                               0.055556   
2                               0.055556   
3                               0.055556   
4                               0.027778   

   ventas_totales_tienda_y_sku_del_mes_pasado  \
0                                         741   
1                                         741   
2                                         714   
3                                         239   
4                                         110   

   ventas_totales_tienda_y_sku_2_pasado  ventas_totales_tienda_y_sku_3_pasado  \
0                                   741                                   741   
1                                   741                                   741   
2                                   741                                   741   
3                                   714                                   741   
4                                   239                                   714   

   ventas_promedio_tienda_y_sku_del_mes_pasado  \
0                                     0.413274   
1                                     0.413274   
2                                     0.398215   
3                                     0.133296   
4                                     0.061350   

   ventas_promedio_tienda_y_sku_2_pasado  \
0                               0.413274   
1                               0.413274   
2                              

In [14]:
datos_modelo.shape

(580932, 24)

In [15]:
datos_modelo.columns

Index(['pdv_id', 'mes_id', 'sku_id', 'ventas_totales',
       'y_ventas_siguiente_mes', 'ventas_totales_en_tienda_de_cada_mes',
       'ventas_promedio_en_tienda_de_cada_mes',
       'ventas_totales_en_tienda_de_cada_sku',
       'ventas_promedio_en_tienda_de_cada_sku', 'ventas_totales_1_mes_pasado',
       'ventas_totales_2_meses_pasados', 'ventas_totales_3_meses_pasados',
       'ventas_totales_tienda_y_mes_del_mes_pasado',
       'ventas_totales_tienda_y_mes_2_pasado',
       'ventas_totales_tienda_y_mes_3_pasado',
       'ventas_promedio_tienda_y_mes_del_mes_pasado',
       'ventas_promedio_tienda_y_mes_2_pasado',
       'ventas_promedio_tienda_y_mes_3_pasado',
       'ventas_totales_tienda_y_sku_del_mes_pasado',
       'ventas_totales_tienda_y_sku_2_pasado',
       'ventas_totales_tienda_y_sku_3_pasado',
       'ventas_promedio_tienda_y_sku_del_mes_pasado',
       'ventas_promedio_tienda_y_sku_2_pasado',
       'ventas_promedio_tienda_y_sku_3_pasado'],
      dtype='object')

In [16]:
datos_modelo.head(1)

pdv_id  mes_id  sku_id  ventas_totales  y_ventas_siguiente_mes  \
0       1       0       1               1                       0   

   ventas_totales_en_tienda_de_cada_mes  \
0                                     2   

   ventas_promedio_en_tienda_de_cada_mes  \
0                               0.055556   

   ventas_totales_en_tienda_de_cada_sku  \
0                                   741   

   ventas_promedio_en_tienda_de_cada_sku  ventas_totales_1_mes_pasado  ...  \
0                               0.413274                            1  ...   

   ventas_totales_tienda_y_mes_3_pasado  \
0                                     2   

   ventas_promedio_tienda_y_mes_del_mes_pasado  \
0                                     0.055556   

   ventas_promedio_tienda_y_mes_2_pasado  \
0                               0.055556   

   ventas_promedio_tienda_y_mes_3_pasado  \
0                               0.055556   

   ventas_totales_tienda_y_sku_del_mes_pasado  \
0                                         741   

   ventas_totales_tienda_y_sku_2_pasado  ventas_totales_tienda_y_sku_3_pasado  \
0                                   741                                   741   

   ventas_promedio_tienda_y_sku_del_mes_pasado  \
0                                     0.413274   

   ventas_promedio_tienda_y_sku_2_pasado  \
0                               0.413274   

   ventas_promedio_tienda_y_sku_3_pasado  
0                               0.413274  

[1 rows x 24 columns]

#1. Dividir datos en entrenamiento y prueba

In [17]:
ent_1 = datos_modelo[datos_modelo['mes_id']==0]
prueba_1 = datos_modelo[datos_modelo['mes_id']==1]

In [18]:
ent_1.shape

(64548, 24)

In [19]:
prueba_1.shape

(64548, 24)

#2. Generar índices en Python

In [20]:
ent_1.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_1.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

#Head para ver datos de entrenamiento y pruebas con índices

#3. Dividir ambos conjuntos (entrenamiento y prueba) en variables de entrada (x) y variables de respuesta (y)

In [21]:
ent_x1 = ent_1.iloc[:, ent_1.columns != 'y_ventas_siguiente_mes']
ent_y1 = ent_1.iloc[:, ent_1.columns == 'y_ventas_siguiente_mes']

prueba_x1= prueba_1.iloc[:, prueba_1.columns != 'y_ventas_siguiente_mes']
prueba_y1= prueba_1.iloc[:, prueba_1.columns == 'y_ventas_siguiente_mes']

#visualizar lo que hicimos anteriormente 

#1. DIVIR DATOS EN ENTRENAMIENTO Y PRUEBA

In [22]:
ent_2 = datos_modelo[datos_modelo['mes_id']<=1]
prueba_2 = datos_modelo[datos_modelo['mes_id']==2]

In [23]:
ent_2.shape

(129096, 24)

In [24]:
prueba_2.shape

(64548, 24)

In [25]:
ent_2.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_2.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [26]:
ent_x2 = ent_2.iloc[:, ent_2.columns != 'y_ventas_siguiente_mes']
ent_y2 = ent_2.iloc[:, ent_2.columns == 'y_ventas_siguiente_mes']

prueba_x2= prueba_2.iloc[:, prueba_2.columns != 'y_ventas_siguiente_mes']
prueba_y2= prueba_2.iloc[:, prueba_2.columns == 'y_ventas_siguiente_mes']

#Iteración 3

In [27]:
ent_3 = datos_modelo[datos_modelo['mes_id']<=2]
prueba_3 = datos_modelo[datos_modelo['mes_id']==3]

In [28]:
ent_3.shape

(193644, 24)

In [29]:
prueba_3.shape

(64548, 24)

In [30]:
ent_3.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_3.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [31]:
ent_x3 = ent_3.iloc[:, ent_3.columns != 'y_ventas_siguiente_mes']
ent_y3 = ent_3.iloc[:, ent_3.columns == 'y_ventas_siguiente_mes']

prueba_x3= prueba_3.iloc[:, prueba_3.columns != 'y_ventas_siguiente_mes']
prueba_y3= prueba_3.iloc[:, prueba_3.columns == 'y_ventas_siguiente_mes']

#Iteración 4

In [32]:
ent_4 = datos_modelo[datos_modelo['mes_id']<=3]
prueba_4 = datos_modelo[datos_modelo['mes_id']==4]

In [33]:
ent_4.shape

(258192, 24)

In [34]:
prueba_4.shape

(64548, 24)

In [35]:
ent_4.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_4.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [36]:
ent_x4 = ent_4.iloc[:, ent_4.columns != 'y_ventas_siguiente_mes']
ent_y4 = ent_4.iloc[:, ent_4.columns == 'y_ventas_siguiente_mes']

prueba_x4= prueba_4.iloc[:, prueba_4.columns != 'y_ventas_siguiente_mes']
prueba_y4= prueba_4.iloc[:, prueba_4.columns == 'y_ventas_siguiente_mes']

#Iteración 5

In [37]:
ent_5 = datos_modelo[datos_modelo['mes_id']<=4]
prueba_5 = datos_modelo[datos_modelo['mes_id']==5]

In [38]:
ent_5.shape

(322740, 24)

In [39]:
prueba_5.shape

(64548, 24)

In [40]:
ent_5.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_5.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [41]:
ent_x5 = ent_5.iloc[:, ent_5.columns != 'y_ventas_siguiente_mes']
ent_y5 = ent_5.iloc[:, ent_5.columns == 'y_ventas_siguiente_mes']

prueba_x5= prueba_5.iloc[:, prueba_5.columns != 'y_ventas_siguiente_mes']
prueba_y5= prueba_5.iloc[:, prueba_5.columns == 'y_ventas_siguiente_mes']

#Iteración 6

In [42]:
ent_6 = datos_modelo[datos_modelo['mes_id']<=5]
prueba_6 = datos_modelo[datos_modelo['mes_id']==6]

In [43]:
ent_6.shape

(387288, 24)

In [44]:
prueba_6.shape

(64548, 24)

In [45]:
ent_6.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_6.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [46]:
ent_x6 = ent_6.iloc[:, ent_6.columns != 'y_ventas_siguiente_mes']
ent_y6 = ent_6.iloc[:, ent_6.columns == 'y_ventas_siguiente_mes']

prueba_x6= prueba_6.iloc[:, prueba_6.columns != 'y_ventas_siguiente_mes']
prueba_y6= prueba_6.iloc[:, prueba_6.columns == 'y_ventas_siguiente_mes']

#Iteración 7

In [47]:
ent_7 = datos_modelo[datos_modelo['mes_id']<=6]
prueba_7 = datos_modelo[datos_modelo['mes_id']==7]

In [48]:
ent_7.shape

(451836, 24)

In [49]:
prueba_7.shape

(64548, 24)

In [50]:
ent_7.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_7.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [51]:
ent_x7 = ent_7.iloc[:, ent_7.columns != 'y_ventas_siguiente_mes']
ent_y7 = ent_7.iloc[:, ent_7.columns == 'y_ventas_siguiente_mes']

prueba_x7= prueba_7.iloc[:, prueba_7.columns != 'y_ventas_siguiente_mes']
prueba_y7= prueba_7.iloc[:, prueba_7.columns == 'y_ventas_siguiente_mes']

#Iteración 8

In [52]:
ent_8 = datos_modelo[datos_modelo['mes_id']<=7]
prueba_8 = datos_modelo[datos_modelo['mes_id']==8]

In [53]:
ent_8.shape

(516384, 24)

In [54]:
prueba_8.shape

(64548, 24)

In [55]:
ent_8.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)
prueba_8.set_index(['pdv_id', 'mes_id','sku_id'], inplace=True)

In [56]:
ent_x8 = ent_8.iloc[:, ent_8.columns != 'y_ventas_siguiente_mes']
ent_y8 = ent_8.iloc[:, ent_8.columns == 'y_ventas_siguiente_mes']

prueba_x8= prueba_8.iloc[:, prueba_8.columns != 'y_ventas_siguiente_mes']
prueba_y8= prueba_8.iloc[:, prueba_8.columns == 'y_ventas_siguiente_mes']

## Parte 3 Modelado

In [57]:
import numpy as np #determinar un rango de valores "clip"
from sklearn import tree #importar función para construir árboles
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error #errores que queremos calcular 
#from scipy.stats import sem
import warnings; warnings.simplefilter('ignore')#WARNING EN 3.3

### Parte 3.1 Entrenar Modelo 

#1 Construir Modelo

In [401]:
modelo_1 = tree.DecisionTreeRegressor(max_depth=1)

In [402]:
ent_x1.head()

ventas_totales  ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                                         
1      0      1                    1                                     2   
              2                    1                                     2   
              3                    0                                     2   
              4                    0                                     2   
              5                    0                                     2   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.055556   
              2                                    0.055556   
              3                                    0.055556   
              4                                    0.055556   
              5                                    0.055556   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      0      1                                        741   
              2                                       1208   
              3                                          0   
              4                                          0   
              5                                          0   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.413274   
              2                                    0.673731   
              3                                    0.000000   
              4                                    0.000000   
              5                                    0.000000   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      0      1                                 1   
              2                                 1   
              3                                 0   
              4                                 0   
              5                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
              2                                    1   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
              2                                    1   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                               
1      0      1                                                2   
              2                                                2   
              3                                                2   
              4                                                2   
              5                                                2   

                      ventas_totales_tienda_y_mes_2_pasado  \
pdv_id mes_id sku_id                                         
1      0      1                                          2   
              2                                          2   
              3                                          2   
              4                                          2   
              5                                          2   

                      ventas_totales_tienda_y_mes_3_pasado  \
pdv_id mes_id sku_id    

#2 Entrenamos el modelo

In [403]:
modelo_1.fit(ent_x1, ent_y1)

DecisionTreeRegressor(max_depth=1)

In [404]:
pred1_ent = modelo_1.predict(ent_x1) 
pred1_ent

array([0.11114526, 0.11114526, 0.11114526, ..., 0.11114526, 0.11114526,
       0.11114526])

In [405]:
min(pred1_ent)

0.11114525711944273

In [406]:
pred1_ent = np.clip(pred1_ent,0,20).round() #rango de valores 
pred1_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [407]:
ent_1['ventas_por_mes_pred'] = pred1_ent

In [408]:
ent_1.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      0      1                    1                       0   
              2                    1                       0   
              3                    0                       1   
              4                    0                       0   
              5                    0                       0   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      0      1                                          2   
              2                                          2   
              3                                          2   
              4                                          2   
              5                                          2   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.055556   
              2                                    0.055556   
              3                                    0.055556   
              4                                    0.055556   
              5                                    0.055556   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      0      1                                        741   
              2                                       1208   
              3                                          0   
              4                                          0   
              5                                          0   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.413274   
              2                                    0.673731   
              3                                    0.000000   
              4                                    0.000000   
              5                                    0.000000   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      0      1                                 1   
              2                                 1   
              3                                 0   
              4                                 0   
              5                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
              2                                    1   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
              2                                    1   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      0      1                                                2  ...   
              2                                                2  ...   
              3                                                2  ...   
              4                                                2  ...   
              5                                                2  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      0   

In [409]:
# 3.4 CALCULAR ERRORES CON FUNCIONES DE PAQUETERÍA 

# Mean absolute error (MAE)
ent1_mae = mean_absolute_error(ent_1.y_ventas_siguiente_mes, ent_1.ventas_por_mes_pred)

# Mean squared error (MSE)
ent1_mse = mean_squared_error(ent_1.y_ventas_siguiente_mes, ent_1.ventas_por_mes_pred)

# R-squared scores
ent1_r2 = r2_score(ent_1.y_ventas_siguiente_mes, ent_1.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent1_mae, 6))
print('Mean Squared Error:', round(ent1_mse, 6))
print('R-squared scores:', round(ent1_r2, 6))

Mean Absolute Error: 0.201664
Mean Squared Error: 0.374342
R-squared scores: 0.03367


In [410]:
modelo_2 = tree.DecisionTreeRegressor(max_depth=1)

In [411]:
modelo_2.fit(ent_x2, ent_y2)

DecisionTreeRegressor(max_depth=1)

In [412]:
pred2_ent = modelo_2.predict(ent_x2) 
pred2_ent

array([0.14410616, 0.14410616, 0.14410616, ..., 0.14410616, 0.14410616,
       0.14410616])

In [413]:
min(pred2_ent)

0.14410616331712459

In [414]:
pred2_ent = np.clip(pred2_ent,0,20).round() #rango de valores 
pred2_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [415]:
ent_2['ventas_por_mes_pred'] = pred2_ent

In [416]:
ent_2.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      0      1                    1                       0   
       1      1                    0                       0   
       0      2                    1                       0   
       1      2                    0                       0   
       0      3                    0                       1   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      0      1                                          2   
       1      1                                          1   
       0      2                                          2   
       1      2                                          1   
       0      3                                          2   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.055556   
       1      1                                    0.027778   
       0      2                                    0.055556   
       1      2                                    0.027778   
       0      3                                    0.055556   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      0      1                                        741   
       1      1                                        714   
       0      2                                       1208   
       1      2                                        864   
       0      3                                          0   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.413274   
       1      1                                    0.398215   
       0      2                                    0.673731   
       1      2                                    0.481874   
       0      3                                    0.000000   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      0      1                                 1   
       1      1                                 1   
       0      2                                 1   
       1      2                                 1   
       0      3                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       0      2                                    1   
       1      2                                    1   
       0      3                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       0      2                                    1   
       1      2                                    1   
       0      3                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      0      1                                                2  ...   
       1      1                                                2  ...   
       0      2                                                2  ...   
       1      2                                                2  ...   
       0      3                                                2  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      0   

In [417]:
# 3.4 CALCULAR ERRORES CON FUNCIONES DE PAQUETERÍA 

# Mean absolute error (MAE)
ent2_mae = mean_absolute_error(ent_2.y_ventas_siguiente_mes, ent_2.ventas_por_mes_pred)

# Mean squared error (MSE)
ent2_mse = mean_squared_error(ent_2.y_ventas_siguiente_mes, ent_2.ventas_por_mes_pred)

# R-squared scores
ent2_r2 = r2_score(ent_2.y_ventas_siguiente_mes, ent_2.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent2_mae, 6))
print('Mean Squared Error:', round(ent2_mse, 6))
print('R-squared scores:', round(ent2_r2, 6))

Mean Absolute Error: 0.19463
Mean Squared Error: 0.544448
R-squared scores: 0.108294


In [418]:
modelo_3 = tree.DecisionTreeRegressor(max_depth=1)

In [419]:
modelo_3.fit(ent_x3, ent_y3)

DecisionTreeRegressor(max_depth=1)

In [420]:
pred3_ent = modelo_3.predict(ent_x3) 
pred3_ent

array([0.16939598, 0.16939598, 0.16939598, ..., 0.16939598, 0.16939598,
       0.16939598])

In [421]:
min(pred3_ent)

0.16939598160861624

In [422]:
pred3_ent = np.clip(pred3_ent,0,20).round() #rango de valores 
pred3_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [423]:
ent_3['ventas_por_mes_pred'] = pred3_ent

In [424]:
ent_3.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      0      1                    1                       0   
       1      1                    0                       0   
       2      1                    0                       0   
       0      2                    1                       0   
       1      2                    0                       0   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      0      1                                          2   
       1      1                                          1   
       2      1                                          7   
       0      2                                          2   
       1      2                                          1   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.055556   
       1      1                                    0.027778   
       2      1                                    0.194444   
       0      2                                    0.055556   
       1      2                                    0.027778   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      0      1                                        741   
       1      1                                        714   
       2      1                                        239   
       0      2                                       1208   
       1      2                                        864   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.413274   
       1      1                                    0.398215   
       2      1                                    0.133296   
       0      2                                    0.673731   
       1      2                                    0.481874   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      0      1                                 1   
       1      1                                 1   
       2      1                                 0   
       0      2                                 1   
       1      2                                 1   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       2      1                                    1   
       0      2                                    1   
       1      2                                    1   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       2      1                                    1   
       0      2                                    1   
       1      2                                    1   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      0      1                                                2  ...   
       1      1                                                2  ...   
       2      1                                                1  ...   
       0      2                                                2  ...   
       1      2                                                2  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      0   

In [425]:
# 3.4 CALCULAR ERRORES CON FUNCIONES DE PAQUETERÍA 

# Mean absolute error (MAE)
ent3_mae = mean_absolute_error(ent_3.y_ventas_siguiente_mes, ent_3.ventas_por_mes_pred)

# Mean squared error (MSE)
ent3_mse = mean_squared_error(ent_3.y_ventas_siguiente_mes, ent_3.ventas_por_mes_pred)

# R-squared scores
ent3_r2 = r2_score(ent_3.y_ventas_siguiente_mes, ent_3.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent3_mae, 6))
print('Mean Squared Error:', round(ent3_mse, 6))
print('R-squared scores:', round(ent3_r2, 6))

Mean Absolute Error: 0.206141
Mean Squared Error: 0.625519
R-squared scores: 0.137616


In [426]:
modelo_4 = tree.DecisionTreeRegressor(max_depth=1)

In [427]:
modelo_4.fit(ent_x4, ent_y4)

DecisionTreeRegressor(max_depth=1)

In [428]:
pred4_ent = modelo_4.predict(ent_x4) 
pred4_ent

array([0.16294694, 0.16294694, 0.16294694, ..., 0.16294694, 0.16294694,
       0.16294694])

In [429]:
min(pred4_ent)

0.1629469396133168

In [430]:
pred4_ent = np.clip(pred4_ent,0,20).round() #rango de valores 
pred4_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [431]:
ent_4['ventas_por_mes_pred'] = pred4_ent

In [432]:
ent_4.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      0      1                    1                       0   
       1      1                    0                       0   
       2      1                    0                       0   
       3      1                    0                       0   
       0      2                    1                       0   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      0      1                                          2   
       1      1                                          1   
       2      1                                          7   
       3      1                                          7   
       0      2                                          2   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.055556   
       1      1                                    0.027778   
       2      1                                    0.194444   
       3      1                                    0.194444   
       0      2                                    0.055556   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      0      1                                        741   
       1      1                                        714   
       2      1                                        239   
       3      1                                        110   
       0      2                                       1208   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.413274   
       1      1                                    0.398215   
       2      1                                    0.133296   
       3      1                                    0.061350   
       0      2                                    0.673731   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      0      1                                 1   
       1      1                                 1   
       2      1                                 0   
       3      1                                 0   
       0      2                                 1   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       2      1                                    1   
       3      1                                    0   
       0      2                                    1   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       2      1                                    1   
       3      1                                    1   
       0      2                                    1   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      0      1                                                2  ...   
       1      1                                                2  ...   
       2      1                                                1  ...   
       3      1                                                7  ...   
       0      2                                                2  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      0   

In [433]:
# 3.4 CALCULAR ERRORES CON FUNCIONES DE PAQUETERÍA 

# Mean absolute error (MAE)
ent4_mae = mean_absolute_error(ent_4.y_ventas_siguiente_mes, ent_4.ventas_por_mes_pred)

# Mean squared error (MSE)
ent4_mse = mean_squared_error(ent_4.y_ventas_siguiente_mes, ent_4.ventas_por_mes_pred)

# R-squared scores
ent4_r2 = r2_score(ent_4.y_ventas_siguiente_mes, ent_4.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent4_mae, 6))
print('Mean Squared Error:', round(ent4_mse, 6))
print('R-squared scores:', round(ent4_r2, 6))

Mean Absolute Error: 0.208132
Mean Squared Error: 0.691485
R-squared scores: 0.174994


In [434]:
modelo_5 = tree.DecisionTreeRegressor(max_depth=1)

In [435]:
modelo_5.fit(ent_x5, ent_y5)

DecisionTreeRegressor(max_depth=1)

In [436]:
pred5_ent = modelo_5.predict(ent_x5) 
pred5_ent

array([0.19255481, 0.19255481, 0.19255481, ..., 0.19255481, 0.19255481,
       0.19255481])

In [437]:
min(pred5_ent)

0.19255481449690331

In [438]:
pred5_ent = np.clip(pred5_ent,0,20).round() #rango de valores 
pred5_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [439]:
ent_5['ventas_por_mes_pred'] = pred5_ent

In [440]:
ent_5.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      0      1                    1                       0   
       1      1                    0                       0   
       2      1                    0                       0   
       3      1                    0                       0   
       4      1                    0                       0   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      0      1                                          2   
       1      1                                          1   
       2      1                                          7   
       3      1                                          7   
       4      1                                         12   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.055556   
       1      1                                    0.027778   
       2      1                                    0.194444   
       3      1                                    0.194444   
       4      1                                    0.333333   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      0      1                                        741   
       1      1                                        714   
       2      1                                        239   
       3      1                                        110   
       4      1                                         58   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.413274   
       1      1                                    0.398215   
       2      1                                    0.133296   
       3      1                                    0.061350   
       4      1                                    0.032348   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      0      1                                 1   
       1      1                                 1   
       2      1                                 0   
       3      1                                 0   
       4      1                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       2      1                                    1   
       3      1                                    0   
       4      1                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       2      1                                    1   
       3      1                                    1   
       4      1                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      0      1                                                2  ...   
       1      1                                                2  ...   
       2      1                                                1  ...   
       3      1                                                7  ...   
       4      1                                                7  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      0   

In [441]:
# 3.4 CALCULAR ERRORES CON FUNCIONES DE PAQUETERÍA 

# Mean absolute error (MAE)
ent5_mae = mean_absolute_error(ent_5.y_ventas_siguiente_mes, ent_5.ventas_por_mes_pred)

# Mean squared error (MSE)
ent5_mse = mean_squared_error(ent_5.y_ventas_siguiente_mes, ent_5.ventas_por_mes_pred)

# R-squared scores
ent5_r2 = r2_score(ent_5.y_ventas_siguiente_mes, ent_5.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent5_mae, 6))
print('Mean Squared Error:', round(ent5_mse, 6))
print('R-squared scores:', round(ent5_r2, 6))

Mean Absolute Error: 0.230232
Mean Squared Error: 0.825473
R-squared scores: 0.196574


In [442]:
modelo_6 = tree.DecisionTreeRegressor(max_depth=1)

In [443]:
modelo_6.fit(ent_x6, ent_y6)

DecisionTreeRegressor(max_depth=1)

In [444]:
pred6_ent = modelo_6.predict(ent_x6) 
pred6_ent

array([0.23008949, 0.23008949, 0.23008949, ..., 0.23008949, 0.23008949,
       0.23008949])

In [445]:
min(pred6_ent)

0.23008949101819903

In [446]:
pred6_ent = np.clip(pred6_ent,0,20).round() #rango de valores 
pred6_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [447]:
ent_6['ventas_por_mes_pred'] = pred6_ent

In [448]:
ent_6.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      0      1                    1                       0   
       1      1                    0                       0   
       2      1                    0                       0   
       3      1                    0                       0   
       4      1                    0                       0   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      0      1                                          2   
       1      1                                          1   
       2      1                                          7   
       3      1                                          7   
       4      1                                         12   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.055556   
       1      1                                    0.027778   
       2      1                                    0.194444   
       3      1                                    0.194444   
       4      1                                    0.333333   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      0      1                                        741   
       1      1                                        714   
       2      1                                        239   
       3      1                                        110   
       4      1                                         58   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.413274   
       1      1                                    0.398215   
       2      1                                    0.133296   
       3      1                                    0.061350   
       4      1                                    0.032348   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      0      1                                 1   
       1      1                                 1   
       2      1                                 0   
       3      1                                 0   
       4      1                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       2      1                                    1   
       3      1                                    0   
       4      1                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       2      1                                    1   
       3      1                                    1   
       4      1                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      0      1                                                2  ...   
       1      1                                                2  ...   
       2      1                                                1  ...   
       3      1                                                7  ...   
       4      1                                                7  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      0   

In [449]:
# 3.4 CALCULAR ERRORES CON FUNCIONES DE PAQUETERÍA 

# Mean absolute error (MAE)
ent6_mae = mean_absolute_error(ent_6.y_ventas_siguiente_mes, ent_6.ventas_por_mes_pred)

# Mean squared error (MSE)
ent6_mse = mean_squared_error(ent_6.y_ventas_siguiente_mes, ent_6.ventas_por_mes_pred)

# R-squared scores
ent6_r2 = r2_score(ent_6.y_ventas_siguiente_mes, ent_6.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent6_mae, 6))
print('Mean Squared Error:', round(ent6_mse, 6))
print('R-squared scores:', round(ent6_r2, 6))

Mean Absolute Error: 0.276084
Mean Squared Error: 1.136353
R-squared scores: 0.165009


In [450]:
modelo_7 = tree.DecisionTreeRegressor(max_depth=1)

In [451]:
modelo_7.fit(ent_x7, ent_y7)

DecisionTreeRegressor(max_depth=1)

In [452]:
pred7_ent = modelo_7.predict(ent_x7) 
pred7_ent

array([0.20459177, 0.20459177, 0.20459177, ..., 0.20459177, 0.20459177,
       0.20459177])

In [453]:
min(pred7_ent)

0.20459177051621555

In [454]:
pred7_ent = np.clip(pred7_ent,0,20).round() #rango de valores 
pred7_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [455]:
ent_7['ventas_por_mes_pred'] = pred7_ent

In [456]:
ent_7.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      0      1                    1                       0   
       1      1                    0                       0   
       2      1                    0                       0   
       3      1                    0                       0   
       4      1                    0                       0   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      0      1                                          2   
       1      1                                          1   
       2      1                                          7   
       3      1                                          7   
       4      1                                         12   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.055556   
       1      1                                    0.027778   
       2      1                                    0.194444   
       3      1                                    0.194444   
       4      1                                    0.333333   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      0      1                                        741   
       1      1                                        714   
       2      1                                        239   
       3      1                                        110   
       4      1                                         58   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.413274   
       1      1                                    0.398215   
       2      1                                    0.133296   
       3      1                                    0.061350   
       4      1                                    0.032348   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      0      1                                 1   
       1      1                                 1   
       2      1                                 0   
       3      1                                 0   
       4      1                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       2      1                                    1   
       3      1                                    0   
       4      1                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       2      1                                    1   
       3      1                                    1   
       4      1                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      0      1                                                2  ...   
       1      1                                                2  ...   
       2      1                                                1  ...   
       3      1                                                7  ...   
       4      1                                                7  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      0   

In [457]:
# 3.4 CALCULAR ERRORES CON FUNCIONES DE PAQUETERÍA 

# Mean absolute error (MAE)
ent7_mae = mean_absolute_error(ent_7.y_ventas_siguiente_mes, ent_7.ventas_por_mes_pred)

# Mean squared error (MSE)
ent7_mse = mean_squared_error(ent_7.y_ventas_siguiente_mes, ent_7.ventas_por_mes_pred)

# R-squared scores
ent7_r2 = r2_score(ent_7.y_ventas_siguiente_mes, ent_7.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent7_mae, 6))
print('Mean Squared Error:', round(ent7_mse, 6))
print('R-squared scores:', round(ent7_r2, 6))

Mean Absolute Error: 0.276029
Mean Squared Error: 1.096371
R-squared scores: 0.140799


In [458]:
modelo_8 = tree.DecisionTreeRegressor(max_depth=1)

In [459]:
modelo_8.fit(ent_x8, ent_y8)

DecisionTreeRegressor(max_depth=1)

In [460]:
pred8_ent = modelo_8.predict(ent_x8) 
pred8_ent

array([0.19234783, 0.19234783, 0.19234783, ..., 0.19234783, 0.19234783,
       0.19234783])

In [461]:
min(pred8_ent)

0.19234783093609717

In [462]:
pred8_ent = np.clip(pred8_ent,0,20).round() #rango de valores 
pred8_ent

array([0., 0., 0., ..., 0., 0., 0.])

In [463]:
ent_8['ventas_por_mes_pred'] = pred8_ent

In [464]:
ent_8.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      0      1                    1                       0   
       1      1                    0                       0   
       2      1                    0                       0   
       3      1                    0                       0   
       4      1                    0                       0   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      0      1                                          2   
       1      1                                          1   
       2      1                                          7   
       3      1                                          7   
       4      1                                         12   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.055556   
       1      1                                    0.027778   
       2      1                                    0.194444   
       3      1                                    0.194444   
       4      1                                    0.333333   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      0      1                                        741   
       1      1                                        714   
       2      1                                        239   
       3      1                                        110   
       4      1                                         58   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      0      1                                    0.413274   
       1      1                                    0.398215   
       2      1                                    0.133296   
       3      1                                    0.061350   
       4      1                                    0.032348   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      0      1                                 1   
       1      1                                 1   
       2      1                                 0   
       3      1                                 0   
       4      1                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       2      1                                    1   
       3      1                                    0   
       4      1                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      0      1                                    1   
       1      1                                    1   
       2      1                                    1   
       3      1                                    1   
       4      1                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      0      1                                                2  ...   
       1      1                                                2  ...   
       2      1                                                1  ...   
       3      1                                                7  ...   
       4      1                                                7  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      0   

In [465]:
# 3.4 CALCULAR ERRORES CON FUNCIONES DE PAQUETERÍA 

# Mean absolute error (MAE)
ent8_mae = mean_absolute_error(ent_8.y_ventas_siguiente_mes, ent_8.ventas_por_mes_pred)

# Mean squared error (MSE)
ent8_mse = mean_squared_error(ent_8.y_ventas_siguiente_mes, ent_8.ventas_por_mes_pred)

# R-squared scores
ent8_r2 = r2_score(ent_8.y_ventas_siguiente_mes, ent_8.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(ent8_mae, 6))
print('Mean Squared Error:', round(ent8_mse, 6))
print('R-squared scores:', round(ent8_r2, 6))

Mean Absolute Error: 0.262131
Mean Squared Error: 1.007913
R-squared scores: 0.130133


In [466]:
pred1_prueba = modelo_1.predict(prueba_x1) 
pred1_prueba

array([0.11114526, 0.11114526, 0.11114526, ..., 0.11114526, 0.11114526,
       0.11114526])

In [467]:
pred1_prueba = np.clip(pred1_prueba,0,20).round() #rango de valores 
pred1_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [468]:
pred1_prueba.sum()

5976.0

In [469]:
prueba_1['ventas_por_mes_pred'] = pred1_prueba

In [470]:
prueba_1.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      1      1                    0                       0   
              2                    0                       0   
              3                    1                       0   
              4                    0                       4   
              5                    0                       1   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      1      1                                          1   
              2                                          1   
              3                                          1   
              4                                          1   
              5                                          1   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      1      1                                    0.027778   
              2                                    0.027778   
              3                                    0.027778   
              4                                    0.027778   
              5                                    0.027778   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      1      1                                        714   
              2                                        864   
              3                                        862   
              4                                        694   
              5                                       1084   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      1      1                                    0.398215   
              2                                    0.481874   
              3                                    0.480759   
              4                                    0.387061   
              5                                    0.604573   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      1      1                                 1   
              2                                 1   
              3                                 0   
              4                                 0   
              5                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      1      1                                    1   
              2                                    1   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      1      1                                    1   
              2                                    1   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      1      1                                                2  ...   
              2                                                2  ...   
              3                                                2  ...   
              4                                                2  ...   
              5                                                2  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      1   

In [471]:
# 4. CALCULAR ERRORES CON FUNCIONES DE PAQUETERÍA

# Mean absolute error (MAE)
prueba1_mae = mean_absolute_error(prueba_1.y_ventas_siguiente_mes, prueba_1.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba1_mse = mean_squared_error(prueba_1.y_ventas_siguiente_mes, prueba_1.ventas_por_mes_pred)

# R-squared scores
prueba1_r2 = r2_score(prueba_1.y_ventas_siguiente_mes, prueba_1.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba1_mae, 6))
print('Mean Squared Error:', round(prueba1_mse, 6))
print('R-squared scores:', round(prueba1_r2, 6))

Mean Absolute Error: 0.260287
Mean Squared Error: 0.809584
R-squared scores: 0.027152


In [472]:
pred2_prueba = modelo_2.predict(prueba_x2) 
pred2_prueba

array([0.14410616, 0.14410616, 0.14410616, ..., 0.14410616, 0.14410616,
       0.14410616])

In [473]:
pred2_prueba = np.clip(pred2_prueba,0,20).round() #rango de valores 
pred2_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [474]:
pred2_prueba.sum()

6088.0

In [475]:
prueba_2['ventas_por_mes_pred'] = pred2_prueba

In [476]:
prueba_2.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      2      1                    0                       0   
              2                    0                       0   
              3                    0                       0   
              4                    4                       1   
              5                    1                       0   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      2      1                                          7   
              2                                          7   
              3                                          7   
              4                                          7   
              5                                          7   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      2      1                                    0.194444   
              2                                    0.194444   
              3                                    0.194444   
              4                                    0.194444   
              5                                    0.194444   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      2      1                                        239   
              2                                        216   
              3                                        859   
              4                                       1794   
              5                                       2329   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      2      1                                    0.133296   
              2                                    0.120468   
              3                                    0.479085   
              4                                    1.000558   
              5                                    1.298940   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      2      1                                 0   
              2                                 0   
              3                                 1   
              4                                 0   
              5                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      2      1                                    1   
              2                                    1   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      2      1                                    1   
              2                                    1   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      2      1                                                1  ...   
              2                                                1  ...   
              3                                                1  ...   
              4                                                1  ...   
              5                                                1  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      2   

In [477]:
# Mean absolute error (MAE)
prueba2_mae = mean_absolute_error(prueba_2.y_ventas_siguiente_mes, prueba_2.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba2_mse = mean_squared_error(prueba_2.y_ventas_siguiente_mes, prueba_2.ventas_por_mes_pred)

# R-squared scores
prueba2_r2 = r2_score(prueba_2.y_ventas_siguiente_mes, prueba_2.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba2_mae, 6))
print('Mean Squared Error:', round(prueba2_mse, 6))
print('R-squared scores:', round(prueba2_r2, 6))

Mean Absolute Error: 0.236754
Mean Squared Error: 0.777747
R-squared scores: 0.183564


In [478]:
pred3_prueba = modelo_3.predict(prueba_x3) 
pred3_prueba

array([0.16939598, 0.16939598, 0.16939598, ..., 0.16939598, 0.16939598,
       0.16939598])

In [479]:
pred3_prueba = np.clip(pred3_prueba,0,20).round() #rango de valores 
pred3_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [480]:
pred3_prueba.sum()

5214.0

In [481]:
prueba_3['ventas_por_mes_pred'] = pred3_prueba

In [482]:
prueba_3.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      3      1                    0                       0   
              2                    0                       0   
              3                    0                       0   
              4                    1                       2   
              5                    0                       3   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      3      1                                          7   
              2                                          7   
              3                                          7   
              4                                          7   
              5                                          7   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      3      1                                    0.194444   
              2                                    0.194444   
              3                                    0.194444   
              4                                    0.194444   
              5                                    0.194444   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      3      1                                        110   
              2                                         94   
              3                                        799   
              4                                       1649   
              5                                       2652   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      3      1                                    0.061350   
              2                                    0.052426   
              3                                    0.445622   
              4                                    0.919688   
              5                                    1.479085   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      3      1                                 0   
              2                                 0   
              3                                 0   
              4                                 4   
              5                                 1   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      3      1                                    0   
              2                                    0   
              3                                    1   
              4                                    0   
              5                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      3      1                                    1   
              2                                    1   
              3                                    0   
              4                                    0   
              5                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      3      1                                                7  ...   
              2                                                7  ...   
              3                                                7  ...   
              4                                                7  ...   
              5                                                7  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      3   

In [483]:
# Mean absolute error (MAE)
prueba3_mae = mean_absolute_error(prueba_3.y_ventas_siguiente_mes, prueba_3.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba3_mse = mean_squared_error(prueba_3.y_ventas_siguiente_mes, prueba_3.ventas_por_mes_pred)

# R-squared scores
prueba3_r2 = r2_score(prueba_3.y_ventas_siguiente_mes, prueba_3.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba3_mae, 6))
print('Mean Squared Error:', round(prueba3_mse, 6))
print('R-squared scores:', round(prueba3_r2, 6))

Mean Absolute Error: 0.214104
Mean Squared Error: 0.889385
R-squared scores: 0.24389


In [484]:
pred4_prueba = modelo_4.predict(prueba_x4) 
pred4_prueba

array([0.16294694, 0.16294694, 0.16294694, ..., 0.16294694, 0.16294694,
       0.16294694])

In [485]:
pred4_prueba = np.clip(pred4_prueba,0,20).round() #rango de valores 
pred4_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [486]:
pred4_prueba.sum()

4686.0

In [487]:
prueba_4['ventas_por_mes_pred'] = pred4_prueba

In [488]:
prueba_4.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      4      1                    0                       0   
              2                    0                       0   
              3                    0                       0   
              4                    2                       2   
              5                    3                       2   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      4      1                                         12   
              2                                         12   
              3                                         12   
              4                                         12   
              5                                         12   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      4      1                                    0.333333   
              2                                    0.333333   
              3                                    0.333333   
              4                                    0.333333   
              5                                    0.333333   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      4      1                                         58   
              2                                         54   
              3                                        383   
              4                                       1570   
              5                                       3685   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      4      1                                    0.032348   
              2                                    0.030117   
              3                                    0.213608   
              4                                    0.875627   
              5                                    2.055215   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      4      1                                 0   
              2                                 0   
              3                                 0   
              4                                 1   
              5                                 0   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      4      1                                    0   
              2                                    0   
              3                                    0   
              4                                    4   
              5                                    1   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      4      1                                    0   
              2                                    0   
              3                                    1   
              4                                    0   
              5                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      4      1                                                7  ...   
              2                                                7  ...   
              3                                                7  ...   
              4                                                7  ...   
              5                                                7  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      4   

In [489]:
# Mean absolute error (MAE)
prueba4_mae = mean_absolute_error(prueba_4.y_ventas_siguiente_mes, prueba_4.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba4_mse = mean_squared_error(prueba_4.y_ventas_siguiente_mes, prueba_4.ventas_por_mes_pred)

# R-squared scores
prueba4_r2 = r2_score(prueba_4.y_ventas_siguiente_mes, prueba_4.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba4_mae, 6))
print('Mean Squared Error:', round(prueba4_mse, 6))
print('R-squared scores:', round(prueba4_r2, 6))

Mean Absolute Error: 0.300583
Mean Squared Error: 1.388393
R-squared scores: 0.217259


In [490]:
pred5_prueba = modelo_5.predict(prueba_x5) 
pred5_prueba

array([0.19255481, 0.19255481, 0.19255481, ..., 0.19255481, 0.19255481,
       0.19255481])

In [491]:
pred5_prueba = np.clip(pred5_prueba,0,20).round() #rango de valores 
pred5_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [492]:
pred5_prueba.sum()

7440.0

In [493]:
prueba_5['ventas_por_mes_pred'] = pred5_prueba

In [494]:
prueba_5.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      5      1                    0                       0   
              2                    0                       0   
              3                    0                       0   
              4                    2                       2   
              5                    2                       2   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      5      1                                         10   
              2                                         10   
              3                                         10   
              4                                         10   
              5                                         10   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      5      1                                    0.277778   
              2                                    0.277778   
              3                                    0.277778   
              4                                    0.277778   
              5                                    0.277778   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      5      1                                         24   
              2                                         22   
              3                                        337   
              4                                       2307   
              5                                       4262   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      5      1                                    0.013385   
              2                                    0.012270   
              3                                    0.187953   
              4                                    1.286670   
              5                                    2.377022   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      5      1                                 0   
              2                                 0   
              3                                 0   
              4                                 2   
              5                                 3   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      5      1                                    0   
              2                                    0   
              3                                    0   
              4                                    1   
              5                                    0   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      5      1                                    0   
              2                                    0   
              3                                    0   
              4                                    4   
              5                                    1   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      5      1                                               12  ...   
              2                                               12  ...   
              3                                               12  ...   
              4                                               12  ...   
              5                                               12  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      5   

In [495]:
# Mean absolute error (MAE)
prueba5_mae = mean_absolute_error(prueba_5.y_ventas_siguiente_mes, prueba_5.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba5_mse = mean_squared_error(prueba_5.y_ventas_siguiente_mes, prueba_5.ventas_por_mes_pred)

# R-squared scores
prueba5_r2 = r2_score(prueba_5.y_ventas_siguiente_mes, prueba_5.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba5_mae, 6))
print('Mean Squared Error:', round(prueba5_mse, 6))
print('R-squared scores:', round(prueba5_r2, 6))

Mean Absolute Error: 0.505345
Mean Squared Error: 2.690757
R-squared scores: 0.092053


In [496]:
pred6_prueba = modelo_6.predict(prueba_x6) 
pred6_prueba

array([0.23008949, 0.23008949, 0.23008949, ..., 0.23008949, 0.23008949,
       0.23008949])

In [497]:
pred6_prueba = np.clip(pred6_prueba,0,20).round() #rango de valores 
pred6_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [498]:
pred6_prueba.sum()

13170.0

In [499]:
prueba_6['ventas_por_mes_pred'] = pred6_prueba

In [500]:
prueba_6.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      6      1                    0                       0   
              2                    0                       0   
              3                    0                       0   
              4                    2                       0   
              5                    2                       1   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      6      1                                         12   
              2                                         12   
              3                                         12   
              4                                         12   
              5                                         12   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      6      1                                    0.333333   
              2                                    0.333333   
              3                                    0.333333   
              4                                    0.333333   
              5                                    0.333333   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      6      1                                         17   
              2                                         18   
              3                                        206   
              4                                       5228   
              5                                       2297   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      6      1                                    0.009481   
              2                                    0.010039   
              3                                    0.114891   
              4                                    2.915784   
              5                                    1.281093   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      6      1                                 0   
              2                                 0   
              3                                 0   
              4                                 2   
              5                                 2   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      6      1                                    0   
              2                                    0   
              3                                    0   
              4                                    2   
              5                                    3   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      6      1                                    0   
              2                                    0   
              3                                    0   
              4                                    1   
              5                                    0   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      6      1                                               10  ...   
              2                                               10  ...   
              3                                               10  ...   
              4                                               10  ...   
              5                                               10  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      6   

In [501]:
# Mean absolute error (MAE)
prueba6_mae = mean_absolute_error(prueba_6.y_ventas_siguiente_mes, prueba_6.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba6_mse = mean_squared_error(prueba_6.y_ventas_siguiente_mes, prueba_6.ventas_por_mes_pred)

# R-squared scores
prueba6_r2 = r2_score(prueba_6.y_ventas_siguiente_mes, prueba_6.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba6_mae, 6))
print('Mean Squared Error:', round(prueba6_mse, 6))
print('R-squared scores:', round(prueba6_r2, 6))

Mean Absolute Error: 0.334232
Mean Squared Error: 1.142685
R-squared scores: -0.49332


In [502]:
pred7_prueba = modelo_7.predict(prueba_x7) 
pred7_prueba

array([0.20459177, 0.20459177, 0.20459177, ..., 0.20459177, 0.20459177,
       0.20459177])

In [503]:
pred7_prueba = np.clip(pred7_prueba,0,20).round() #rango de valores 
pred7_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [504]:
pred7_prueba.sum()

4857.0

In [505]:
prueba_7['ventas_por_mes_pred'] = pred7_prueba

In [506]:
prueba_7.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      7      1                    0                       0   
              2                    0                       0   
              3                    0                       0   
              4                    0                       0   
              5                    1                       0   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      7      1                                         14   
              2                                         14   
              3                                         14   
              4                                         14   
              5                                         14   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      7      1                                    0.388889   
              2                                    0.388889   
              3                                    0.388889   
              4                                    0.388889   
              5                                    0.388889   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      7      1                                         17   
              2                                         12   
              3                                        163   
              4                                        425   
              5                                        558   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      7      1                                    0.009481   
              2                                    0.006693   
              3                                    0.090909   
              4                                    0.237033   
              5                                    0.311210   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      7      1                                 0   
              2                                 0   
              3                                 0   
              4                                 2   
              5                                 2   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      7      1                                    0   
              2                                    0   
              3                                    0   
              4                                    2   
              5                                    2   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      7      1                                    0   
              2                                    0   
              3                                    0   
              4                                    2   
              5                                    3   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      7      1                                               12  ...   
              2                                               12  ...   
              3                                               12  ...   
              4                                               12  ...   
              5                                               12  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      7   

In [507]:
# Mean absolute error (MAE)
prueba7_mae = mean_absolute_error(prueba_7.y_ventas_siguiente_mes, prueba_7.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba7_mse = mean_squared_error(prueba_7.y_ventas_siguiente_mes, prueba_7.ventas_por_mes_pred)

# R-squared scores
prueba7_r2 = r2_score(prueba_7.y_ventas_siguiente_mes, prueba_7.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba7_mae, 6))
print('Mean Squared Error:', round(prueba7_mse, 6))
print('R-squared scores:', round(prueba7_r2, 6))

Mean Absolute Error: 0.164839
Mean Squared Error: 0.388703
R-squared scores: -0.225139


In [508]:
pred8_prueba = modelo_8.predict(prueba_x8) 
pred8_prueba

array([0.19234783, 0.19234783, 0.19234783, ..., 0.19234783, 0.19234783,
       0.19234783])

In [509]:
pred8_prueba = np.clip(pred8_prueba,0,20).round() #rango de valores 
pred8_prueba

array([0., 0., 0., ..., 0., 0., 0.])

In [510]:
pred8_prueba.sum()

1947.0

In [511]:
prueba_8['ventas_por_mes_pred'] = pred8_prueba

In [512]:
prueba_8.head(5)

ventas_totales  y_ventas_siguiente_mes  \
pdv_id mes_id sku_id                                           
1      8      1                    0                       0   
              2                    0                       0   
              3                    0                       0   
              4                    0                       0   
              5                    0                       0   

                      ventas_totales_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                         
1      8      1                                          1   
              2                                          1   
              3                                          1   
              4                                          1   
              5                                          1   

                      ventas_promedio_en_tienda_de_cada_mes  \
pdv_id mes_id sku_id                                          
1      8      1                                    0.027778   
              2                                    0.027778   
              3                                    0.027778   
              4                                    0.027778   
              5                                    0.027778   

                      ventas_totales_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                         
1      8      1                                          5   
              2                                          2   
              3                                        275   
              4                                         70   
              5                                        140   

                      ventas_promedio_en_tienda_de_cada_sku  \
pdv_id mes_id sku_id                                          
1      8      1                                    0.002789   
              2                                    0.001115   
              3                                    0.153374   
              4                                    0.039041   
              5                                    0.078081   

                      ventas_totales_1_mes_pasado  \
pdv_id mes_id sku_id                                
1      8      1                                 0   
              2                                 0   
              3                                 0   
              4                                 0   
              5                                 1   

                      ventas_totales_2_meses_pasados  \
pdv_id mes_id sku_id                                   
1      8      1                                    0   
              2                                    0   
              3                                    0   
              4                                    2   
              5                                    2   

                      ventas_totales_3_meses_pasados  \
pdv_id mes_id sku_id                                   
1      8      1                                    0   
              2                                    0   
              3                                    0   
              4                                    2   
              5                                    2   

                      ventas_totales_tienda_y_mes_del_mes_pasado  ...  \
pdv_id mes_id sku_id                                              ...   
1      8      1                                               14  ...   
              2                                               14  ...   
              3                                               14  ...   
              4                                               14  ...   
              5                                               14  ...   

                      ventas_promedio_tienda_y_mes_del_mes_pasado  \
pdv_id mes_id sku_id                                                
1      8   

In [513]:
# Mean absolute error (MAE)
prueba8_mae = mean_absolute_error(prueba_8.y_ventas_siguiente_mes, prueba_8.ventas_por_mes_pred)

# Mean squared error (MSE)
prueba8_mse = mean_squared_error(prueba_8.y_ventas_siguiente_mes, prueba_8.ventas_por_mes_pred)

# R-squared scores
prueba8_r2 = r2_score(prueba_8.y_ventas_siguiente_mes, prueba_8.ventas_por_mes_pred)


# Print metrics
print('Mean Absolute Error:', round(prueba8_mae, 6))
print('Mean Squared Error:', round(prueba8_mse, 6))
print('R-squared scores:', round(prueba8_r2, 6))

Mean Absolute Error: 0.081149
Mean Squared Error: 0.174909
R-squared scores: -0.181061
